services:
  webtaller:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
      args:
        - PROYECTO=${PROYECTO}
        - USUARIO=${USUARIO}
        - TIPO=${TIPO}
    image: ${FIRMA}/ub${PROYECTO}
    container_name: ctwebtaller
    